apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osrm-data-pvc
  namespace: bock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
