apiVersion: v1
kind: ConfigMap
metadata:
  name: bockdocs-config
  namespace: bock
data:
  NODE_ENV: "development"
  PORT: "5050"
  HOST: "0.0.0.0"
  FRONTEND_URL: "http://localhost:3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: bockdocs-secrets
  namespace: bock
type: Opaque
stringData:
  DATABASE_URL: "postgresql://bockdocs_user:Bock7892@bockdb.cdo8cys6ugtx.ap-south-1.rds.amazonaws.com:5432/bockdocs_db?schema=public&sslmode=verify-full&sslrootcert=/certs/global-bundle.pem"
  JWT_SECRET: "BockEBengaluru"
  GOOGLE_CLIENT_ID: "33941110911-3tvbuphsr3e1g2nvp3njknmj0p1koilh.apps.googleusercontent.com"
  EMAIL_SERVICE: "gmail"
  EMAIL_USER: "chavandarshan24@gmail.com"
  EMAIL_PASSWORD: "yivh getv gkpq lyvx"
  EMAIL_FROM: "noreply@bockdocs.com"


