# =============================================================================
# POSTGRES KUBERNETES MANIFEST
# =============================================================================
# >>> KEEP when using k8s postgres
# >>> DELETE when switching to AWS RDS (along with other postgres-*.yaml files)
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bock
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Bock7892"
