apiVersion: v1
kind: Service
metadata:
  name: krysonix-backend
  namespace: bock
  labels:
    app: krysonix-backend
spec:
  type: ClusterIP
  selector:
    app: krysonix-backend
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
