apiVersion: v1
kind: Service
metadata:
  name: bockvote-backend
  namespace: bock
  labels:
    app: bockvote-backend
spec:
  type: ClusterIP
  selector:
    app: bockvote-backend
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
