-- Add OTP fields to User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "otp" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "otpExpiry" TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
