apiVersion: v1
kind: ConfigMap
metadata:
  name: map-api-keygen-config
  namespace: demo
data:
  NODE_ENV: production
  PORT: "3000"
  REDIS_URL: redis://map-redis:6379
  CORS_ORIGINS: "http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001,http://192.168.49.2:31839"
